- hosts: all
  become: true
  tasks:

  - name: install apache2
    ansible.builtin.package:
      name: "{{ apache_package }}"
      state: latest
      update_cache: yes

  - name: start apache2
    service:
      name: "{{ apache_package }}"
      state: started
      enabled: yes
